# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [109]:
import numpy as np

In [110]:
# 1차원 배열
arr=np.arange(1, 11)  # 1~10까지
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr[1], arr[4], arr[-1]

(2, 5, 10)

In [112]:
# 2차원 배열
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
arr2[0][1], arr2[1][2], arr2[-1][-1]

(2, 7, 12)

In [114]:
# 다차원 indexing
arr2[0, 1], arr2[1, 2], arr2[-1, -1]

(2, 7, 12)

## 5-2. 슬라이싱

In [115]:
# 1차원 배열
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
# 슬라이싱 [start:end:step]
arr[2:6]

array([3, 4, 5, 6])

In [117]:
# 3~끝까지
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
# 처음~6까지
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [119]:
# 처음~끝까지
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
# 슬라이싱한 후 값을 변경하면 원본 배열에 영향을 미칠까?
new_arr = arr[2:6]
new_arr

array([3, 4, 5, 6])

In [121]:
new_arr[0] = 100
new_arr

array([100,   4,   5,   6])

In [122]:
arr

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [123]:
copy_arr = np.copy(arr)
copy_arr

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [124]:
arr[::2]

array([  1, 100,   5,   7,   9])

In [125]:
# 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
# 첫번째 행을 가져오기
arr2[0, :]

array([1, 2, 3, 4])

In [127]:
# 세번째 열을 가져오기
arr2[:, 2]

array([ 3,  7, 11])

In [128]:
# 첫번째, 두번째행을 가져오기
arr2[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [129]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
# 두번째, 세번째 열을 가져오기
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [131]:
arr2[:2, 1:-1]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

In [132]:
# 1차원
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
# [3, 6, 8]로 된 1차원 배열 만들기
np.array([arr[2], arr[5], arr[7]])

array([3, 6, 8])

In [134]:
# Fancy 인덱싱
# 인덱스로 배열 만들기
arr[[2, 5, 7]]

array([3, 6, 8])

In [135]:
# 2차원 배열
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [136]:
arr2[[0, 2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [137]:
arr2[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [138]:
# Fancy 인덱싱
arr2[:, [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 5-4. Boolean 인덱싱

In [139]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [140]:
cond = [True, True, False, False, True]

In [141]:
# Boolean 인덱싱
arr[cond]

array([0, 1, 4])

In [142]:
arr[arr > 2]

array([3, 4])

In [145]:
# 짝수 뽑기
arr[arr%2 == 0]

array([0, 2, 4])

In [146]:
arr % 2 == 0

array([ True, False,  True, False,  True])

In [147]:
arr[arr % 2 == 0]

array([0, 2, 4])

In [152]:
# 1보다 작거나 3보다 큰 수 (0, 4)
(arr < 1) | (arr > 3)

array([ True, False, False, False,  True])

In [153]:
arr[(arr < 1) | (arr > 3)]

array([0, 4])

In [156]:
# 2이상 3이하인 수 (2, 3)
arr[(arr >= 2) & (arr <= 3)]

array([2, 3])