# 6. 실습

In [78]:
# numpy import하기
import numpy as np

## 6-1. NumPy 배열 생성

In [79]:
# np.array()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [80]:
# 1차원 배열의 데이터타입, 모양, 배열 전체 element의 수, 차원의 수 출력하기
arr.dtype

dtype('int32')

In [81]:
arr.shape

(5,)

In [82]:
arr.size

5

In [83]:
# np.array()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr2 = np.array([10, 20, 30, 40, 50, 60, 70, 80]).reshape(2, 4)
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [84]:
# np.arange()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr = np.arange(1, 6)
arr

array([1, 2, 3, 4, 5])

In [85]:
# np.arange()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr2 = np.arange(10, 90, 10).reshape(2, 4)
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [86]:
# 주사위를 100번 던져서 나오는 숫자 배열 출력하기
np.random.randint(1, 7, size=100)

array([3, 6, 5, 4, 5, 2, 3, 3, 3, 4, 1, 1, 5, 1, 5, 3, 6, 2, 6, 3, 4, 4,
       3, 5, 6, 6, 6, 6, 5, 2, 5, 5, 4, 5, 4, 4, 3, 4, 5, 1, 6, 1, 4, 2,
       6, 6, 1, 3, 4, 5, 5, 3, 1, 2, 1, 3, 5, 3, 2, 4, 6, 3, 4, 3, 1, 3,
       3, 6, 1, 2, 3, 3, 4, 3, 2, 2, 1, 4, 3, 2, 1, 3, 2, 4, 5, 4, 4, 1,
       5, 1, 5, 5, 3, 5, 1, 3, 5, 4, 3, 1])

In [87]:
# np.random을 사용하여 랜덤 실수값으로 이루어진 (3, 4) 2차원 배열 생성
np.random.rand(3, 4)

array([[0.75204748, 0.38037649, 0.78955254, 0.12503067],
       [0.09103331, 0.71941224, 0.18847105, 0.04024489],
       [0.61725402, 0.99399599, 0.27409885, 0.35394354]])

## 6-2. 산술연산

In [88]:
# [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] 1차원 배열 2개를 생성하고 출력하기
arr = np.arange(1, 6)
arr2 = np.arange(6, 11)
arr, arr2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [89]:
# 1차원 배열간 산술연산(덧셈, 뺄셈, 곱셈, 나눗셈) 하기
arr + arr2

array([ 7,  9, 11, 13, 15])

In [90]:
arr - arr2

array([-5, -5, -5, -5, -5])

In [91]:
arr * arr2

array([ 6, 14, 24, 36, 50])

In [92]:
arr / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [128]:
# [[1, 2, 3, 4, 5]   [[11, 12, 13, 14, 15]
#  [6, 7, 8, 9, 10]], [16, 17, 18, 19, 20]] 2차원 배열 2개를 생성하고 출력하기
arr = np.arange(1, 11).reshape(2, 5)
arr2 = np.arange(11, 21).reshape(2, 5)
arr, arr2

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [129]:
# 2차원 배열간 산술연산(덧셈, 뺄셈, 나눗셈) 하기
arr + arr2

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [130]:
arr - arr2

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [131]:
arr / arr2

array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
       [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]])

In [132]:
# 두번째 배열의 shape을 (5, 2)로 만들고 출력하기
arr2.reshape(5, 2)

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [144]:
# 행렬곱셈(dot product) 연산하기
arr2 = arr2.reshape(5, 2)
arr2

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [145]:
np.dot(arr, arr2)

array([[245, 260],
       [620, 660]])

## 6-3. Aggregation 함수

In [146]:
# 1~10까지 이루어진 1차원 배열 생성하기
arr = np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
# 최대값, 최소값 출력하기
np.min(arr)

1

In [148]:
np.max(arr)

10

In [149]:
# 배열요소의 합, 평균값 출력하기
np.sum(arr)

55

In [150]:
np.mean(arr)

5.5

In [151]:
# 중앙값(중위값), 표준편차 출력하기
np.median(arr)

5.5

In [270]:
# 1~20까지 이루어진 2차원 배열 (4, 5) 생성하기
arr2 = np.arange(1, 21).reshape(4, 5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [271]:
# 각 행의 max값, min값 출력하기
np.max(arr2)

20

In [272]:
np.min(arr2)

1

In [282]:
# 각 열의 max값, min값 출력하기


1

In [279]:
# 각 행의 sum값 출력하기
np.sum(arr2)

210

In [275]:
# 각 열의 sum값 출력하기
np.sum(arr2)

210

## 6-4. 정렬

In [197]:
# 1~100까지 랜덤 정수값을 갖는 1차원 배열 (10, ) 생성하기
# seed값 100부여하기
np.random.seed(100)
arr = np.random.randint(1, 101, size=100)
arr

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99, 54, 67, 99, 15, 35, 25, 16,
       61, 59, 17, 10, 94, 87,  3, 28,  5, 32,  2, 14, 84,  5, 92, 60, 68,
        8, 50, 48, 66, 62, 15, 56, 72, 81,  3, 95, 20, 99, 64, 54, 28, 57,
       31, 49, 48, 40, 39, 45, 19, 65, 57, 35, 54, 75, 18, 73, 14, 31, 18,
       54, 69, 51, 92, 92, 84, 54, 79,  1, 14, 58, 77,  4, 71,  4, 85, 80,
       11, 88, 61,  4, 49, 53, 44, 37,  6, 72, 39, 87, 95, 99, 43])

In [198]:
# 위 1차원 배열을 오름차순 정렬하기
np.sort(arr)

array([ 1,  2,  3,  3,  4,  4,  4,  5,  5,  6,  8,  9, 10, 11, 11, 14, 14,
       14, 15, 15, 16, 17, 18, 18, 19, 20, 25, 25, 28, 28, 31, 31, 32, 35,
       35, 37, 39, 39, 40, 43, 44, 45, 48, 48, 49, 49, 49, 50, 51, 53, 53,
       54, 54, 54, 54, 54, 56, 57, 57, 58, 59, 60, 61, 61, 62, 64, 65, 66,
       67, 68, 68, 69, 71, 72, 72, 73, 75, 77, 79, 80, 80, 81, 84, 84, 85,
       87, 87, 88, 88, 92, 92, 92, 94, 95, 95, 95, 99, 99, 99, 99])

In [199]:
# 위 1차원 배열을 내림차순 정렬하기
np.sort(arr)[::-1]

array([99, 99, 99, 99, 95, 95, 95, 94, 92, 92, 92, 88, 88, 87, 87, 85, 84,
       84, 81, 80, 80, 79, 77, 75, 73, 72, 72, 71, 69, 68, 68, 67, 66, 65,
       64, 62, 61, 61, 60, 59, 58, 57, 57, 56, 54, 54, 54, 54, 54, 53, 53,
       51, 50, 49, 49, 49, 48, 48, 45, 44, 43, 40, 39, 39, 37, 35, 35, 32,
       31, 31, 28, 28, 25, 25, 20, 19, 18, 18, 17, 16, 15, 15, 14, 14, 14,
       11, 11, 10,  9,  8,  6,  5,  5,  4,  4,  4,  3,  3,  2,  1])

In [203]:
# 랜덤 seed값 100부여하기
# 1~100까지 랜덤 정수값을 갖는 2차원 배열 (5, 10) 생성하기
np.random.seed(100)
arr2 = np.random.randint(1, 101, size=50).reshape(5, 10)
arr2

array([[ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35, 25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28,  5, 32,  2, 14, 84],
       [ 5, 92, 60, 68,  8, 50, 48, 66, 62, 15],
       [56, 72, 81,  3, 95, 20, 99, 64, 54, 28]])

In [206]:
# 열 기준 정렬하기
np.sort(arr2, axis=1)

array([[ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99],
       [15, 16, 17, 25, 35, 54, 59, 61, 67, 99],
       [ 2,  3,  5, 10, 14, 28, 32, 84, 87, 94],
       [ 5,  8, 15, 48, 50, 60, 62, 66, 68, 92],
       [ 3, 20, 28, 54, 56, 64, 72, 81, 95, 99]])

In [207]:
# 행 기준 정렬하기
np.sort(arr2, axis=0)

array([[ 5, 25, 60,  3,  8,  5, 11,  2, 14, 15],
       [ 9, 67, 68,  3, 28, 20, 16, 61, 53, 17],
       [10, 72, 81, 15, 35, 25, 32, 64, 54, 28],
       [54, 92, 87, 68, 80, 49, 48, 66, 59, 84],
       [56, 94, 99, 88, 95, 50, 99, 95, 62, 99]])

## 6-5. 인덱싱과 슬라이싱

In [212]:
# 0~14로 이루어진 2차원 배열 (3, 5) 생성하기
arr2 = np.arange(0, 15).reshape(3, 5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [217]:
# 위 배열에서 7을 인덱싱하기
arr2[1, 2]

7

In [236]:
# 위 배열에서 14를 인덱싱하기 (음수 인덱스 사용)
arr2[-1, -1]

14

In [239]:
# 위 배열에서 배열 [6, 7]을 슬라이싱하기
arr2[1, 1:3]

array([6, 7])

In [253]:
# 위 배열에서 배열 [7, 12]을 슬라이싱하기
arr2[1:3, 2]

array([ 7, 12])

In [260]:
# 위 배열에서 [[3, 4], [8, 9]]을 슬라이싱하기
arr2[0:2, 3:5]

array([[3, 4],
       [8, 9]])

In [266]:
# 위 배열에서 3의 배수 찾기
arr2[arr2%3 == 0]

array([ 0,  3,  6,  9, 12])

In [267]:
# 위 배열에서 4로 나누면 1이 남는 수 찾기
arr2[arr2%4 == 1]

array([ 1,  5,  9, 13])

In [268]:
# 위 배열에서 3의 배수이면서 4로 나누면 1이 남는 수 찾기
arr2[(arr2%3 == 0) & arr2%4 == 1]

array([3, 9])